import type { Metadata } from "next";
import { Roboto } from 'next/font/google'

import "./globals.css";

const roboto = Roboto({
  weight: '500',
  subsets: ['latin'],
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sections: Array<{ title: string, href: string }> = [
    {
      title: 'About',
      href: '/about'
    },
    {
      title: 'Projects',
      href: '/projects'
    },
  ]
  return (
    <html lang="en" className='h-full'>
      <body className={roboto.className + ' h-full'}>
        {/* <nav className='h-1/6 w-full flex flex-row items-center'>
            {sections.map((section) =>
              <div key={section.href} className='w-1/2 text-center m-auto'>
                <a href={section.href}>
                  {section.title}
                </a>
              </div>
            )}
          </nav> */}
          {children}
      </body>
    </html>
  );
}
